#pragma once

#ifdef DEKI_EDITOR

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

#include "../Mesh3D.h"  // TexelFormat

namespace Deki3D
{

/// Turns Wavefront .obj text into the compiled mesh blob MeshAsset reads.
///
/// Depends on nothing in the editor or engine beyond the file format, so it
/// can be tested on its own. The editor glue (finding the file, choosing the
/// output path, registering the GUID) lives in Deki3DAssetTypes.cpp.
///
/// Handles `v`, `vt`, `vn`, `f` in the `v`, `v/vt`, `v//vn` and `v/vt/vn`
/// forms, negative (relative) indices, polygons of more than three vertices
/// (fan triangulated), and `usemtl` as a submesh boundary. Anything else on a
/// line is ignored.
///
/// The texture V coordinate is flipped, since .obj measures it from the
/// bottom and the sampler from the top. When the file has no normals, smooth
/// ones are generated by accumulating face normals.
///
/// Textures: `mtllib` is read, and each material's `map_Kd` becomes its
/// texture, decoded once per distinct image through the caller's
/// `decodeImage`. Each is scaled to powers of two (the sampler masks rather
/// than divides) and capped, then stored in the blob in the format
/// `chooseFormat` picks (RGB565 when it is empty). A texture with transparent
/// pixels turns its material's alpha test on when its format keeps alpha. An
/// empty `decodeImage` skips textures, which lets the tests run without the
/// editor's image loading.
///
/// Returns false with `error` set on malformed input, or when the mesh needs
/// more than 65535 vertices, which the 16-bit index buffer cannot address.
using ImageDecoder =
    std::function<bool(const std::string& absolutePath, int& outWidth, int& outHeight, std::vector<uint8_t>& outRgba)>;

/// A mesh texture's size cap when its model sets no Max Size. At RGB565 a
/// 256 x 256 texture is 128 KB, already more than a small board wants resident.
constexpr int kDefaultMeshTextureSize = 256;

/// The format to store a texture in, given whether it has transparent pixels.
using TextureFormatChooser = std::function<TexelFormat(bool hasAlpha)>;

/// `maxTextureSize` caps the texture's larger side (its Max Size); the stored
/// sides are the largest powers of two within it.
bool CompileObjToMesh(const std::string& objText, const std::string& baseDirectory, const ImageDecoder& decodeImage,
                      std::vector<uint8_t>& outBlob, std::string& error, const TextureFormatChooser& chooseFormat = {},
                      int maxTextureSize = kDefaultMeshTextureSize);

}  // namespace Deki3D

#endif  // DEKI_EDITOR
