#pragma once

#ifdef DEKI_EDITOR

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

#include "../Mesh3D.h"  // TexelFormat

namespace Deki3D
{

/// Turn Wavefront .obj text into the compiled mesh blob MeshAsset reads.
///
/// Deliberately free of any editor or engine dependency beyond the file
/// format itself, so it can be exercised on its own. The editor glue that
/// finds the file, picks the output path and registers the GUID lives
/// elsewhere.
///
/// What it handles: `v`, `vt`, `vn`, `f` with any of the `v`, `v/vt`,
/// `v//vn`, `v/vt/vn` forms, negative (relative) indices, polygons of more
/// than three vertices (fan triangulated), and `usemtl` as a submesh
/// boundary. Everything else on a line is ignored.
///
/// Two conversions happen because the rest of the pipeline expects them:
/// the texture V coordinate is flipped, since .obj measures it from the
/// bottom and the sampler measures from the top; and when the file carries
/// no normals, smooth ones are generated by accumulating face normals.
///
/// Textures: `mtllib` is read, and the first `map_Kd` found becomes the mesh's
/// texture. It is decoded through the caller's `decodeImage`, scaled to powers
/// of two (the sampler masks rather than divides) and capped, then stored
/// inside the blob in the format `chooseFormat` picks for it (RGB565 when it
/// is empty); a texture with transparent pixels turns the material's alpha
/// test on when its format keeps alpha. One texture per mesh for now; a model with several
/// materials draws them all with the first. Passing an empty `decodeImage`
/// skips textures entirely, which is what the tests do so the parser stays
/// free of the editor's image loading.
///
/// Returns false with `error` set on malformed input, or when the mesh needs
/// more than 65535 vertices, which the 16-bit index buffer cannot address.
using ImageDecoder = std::function<bool(const std::string& absolutePath, int& outWidth,
                                        int& outHeight, std::vector<uint8_t>& outRgba)>;

/// The format to store a texture in, given whether it has transparent pixels.
using TextureFormatChooser = std::function<TexelFormat(bool hasAlpha)>;

bool CompileObjToMesh(const std::string& objText, const std::string& baseDirectory,
                      const ImageDecoder& decodeImage, std::vector<uint8_t>& outBlob,
                      std::string& error, const TextureFormatChooser& chooseFormat = {});

}  // namespace Deki3D

#endif  // DEKI_EDITOR
