#pragma once

#ifdef DEKI_EDITOR

#include <cstdint>
#include <string>
#include <vector>

namespace Deki3D
{

/// Turn Wavefront .obj text into the compiled mesh blob MeshAsset reads.
///
/// Deliberately free of any editor or engine dependency beyond the file
/// format itself, so it can be exercised on its own. The editor glue that
/// finds the file, picks the output path and registers the GUID lives
/// elsewhere.
///
/// What it handles: `v`, `vt`, `vn`, `f` with any of the `v`, `v/vt`,
/// `v//vn`, `v/vt/vn` forms, negative (relative) indices, polygons of more
/// than three vertices (fan triangulated), and `usemtl` as a submesh
/// boundary. Everything else on a line is ignored.
///
/// Two conversions happen because the rest of the pipeline expects them:
/// the texture V coordinate is flipped, since .obj measures it from the
/// bottom and the sampler measures from the top; and when the file carries
/// no normals, smooth ones are generated by accumulating face normals.
///
/// Returns false with `error` set on malformed input, or when the mesh needs
/// more than 65535 vertices, which the 16-bit index buffer cannot address.
bool CompileObjToMesh(const std::string& objText, std::vector<uint8_t>& outBlob,
                      std::string& error);

}  // namespace Deki3D

#endif  // DEKI_EDITOR
